[package]
name = "sailbreak"
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
publish = false
repository.workspace = true
description = "Cross-platform Lenovo hardware control CLI"

[[bin]]
name = "sailbreak"
path = "src/main.rs"


[dependencies]
clap = { version = "4", features = ["derive"] }
sailbreak-daemon = { path = "../crates/sailbreak-daemon" }
sailbreak-cli = { path = "../crates/sailbreak-cli" }
lctrl-core = { path = "../crates/lctrl-core" }
lctrl-hal = { path = "../crates/lctrl-hal" }
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
lctrl-hal-linux = { path = "../crates/lctrl-hal-linux" }

[target.'cfg(windows)'.dependencies]
lctrl-hal-win = { path = "../crates/lctrl-hal-win" }
