[package]
name = "sailbreak-gui"
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
publish = false
repository.workspace = true
description = "Embedded Proto-UI Shadcn GPUI dashboard for Sailbreak"

[dependencies]
gpui = { version = "=0.2.2", default-features = true, features = ["wayland", "x11"] }
lctrl-core = { path = "../lctrl-core" }
lctrl-hal = { path = "../lctrl-hal" }
proto-ui-gpui = { path = "../proto-ui-gpui" }
sailbreak-cli = { path = "../sailbreak-cli" }
sailbreak-daemon = { path = "../sailbreak-daemon" }
serde_json.workspace = true



[target.'cfg(target_os = "linux")'.dependencies]
lctrl-hal-linux = { path = "../lctrl-hal-linux" }

[target.'cfg(windows)'.dependencies]
lctrl-hal-win = { path = "../lctrl-hal-win" }